   server:
     port: 8082
  
  
   spring:
     datasource:
       url: jdbc:mysql://localhost:3306/microservices
       username: root
       password: codeHustle2210#
       driver-class-name: com.mysql.cj.jdbc.Driver
     config:
       import: configserver:http://localhost:8085
         
       
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
       application:
         name: HOTEL_SERVICE
   logging:
     level:
       org.hibernate.SQL: DEBUG
       org.hibernate.type.descriptor.sql.BasicBinder: TRACE

   eureka:
    instance:
      prefer-ip-address: true      
    client:  
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka    
         