   server:
     port: 8081
  
  
   spring:
     config:
       import: configserver:http://localhost:8085
     datasource:
       url: jdbc:mysql://localhost:3306/microservices
       username: root
       password: codeHustle2210#
       driver-class-name: com.mysql.cj.jdbc.Driver
       
    
       
       
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
       application:
        name: USER_SERVICE
   logging:
     level:
       org.hibernate.SQL: DEBUG
       org.hibernate.type.descriptor.sql.BasicBinder: TRACE
   management:
     health:
      circuitbreakers:
        enabled: true
     endpoints:
        web:
          exposure:
            include: health
     endpoint:
       health:
         show-details: always
   resilience4j:
     circuitbreaker:
       instances:
         ratingHotelBreaker:
           registerHealthIndicator: true
           eventConsumerBufferSize: 10
           failureRateThreshold: 50
           minimumNumberOfCalls: 5
           automaticTransitionFromOpenToHalfOpenEnabled: true
           waitDurationInOpenState: 6s
           permittedNumberOfCallsInHalfOpenState: 3
           slidingWindowSize: 10
           slidingWindowType: COUNT_BASED 
           
     retry:
       instances:
        ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

     ratelimiter:
       instances:
          userRateLimiter:
            limit-refresh-period: 4s
            limit-for-period: 2
            timeout-duration: 2s 
   